server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;

        add_header Content-Security-Policy "frame-ancestors https://service-prompt-to-ui-253404938246.us-central1.run.app" always;
        add_header X-Frame-Options "" always;
    }

    error_page 404 /index.html;
    location = /index.html {
        internal;
    }
}
